[package]
name = "blackjack"
version = "0.0.1"
authors = ["Noah Erickson <noahterickson@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"